stages:
  - build

build:
  stage: build
  image: node:latest
  
  script:
    - yarn install --frozen-lockfile
    - yarn check-types
    - yarn lint
    - yarn build
  artifacts:
    paths:
      - public
    expire_in: 1 hour
  only:
    - andxet.dev
    - merge_requests